version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    # This is a placeholder for the backend service
    # Replace with your actual backend service configuration
    image: node:18-alpine
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 